#Following instructions (as of 2020-04-01): https://docs.gitlab.com/ee/ci/docker/using_kaniko.html
#Kaniko docs are here: https://github.com/GoogleContainerTools/kaniko
image: 
  name: gcr.io/kaniko-project/executor:debug
  entrypoint: [""]

variables: 
  IMAGE_LABELS: >
    --label vcs-url=$CI_PROJECT_URL
    --label com.gitlab.ci.user=$GITLAB_USER_NAME
    --label com.gitlab.ci.email=$GITLAB_USER_EMAIL
    --label com.gitlab.ci.tagorbranch=$CI_COMMIT_REF_NAME
    --label com.gitlab.ci.pipelineurl=$CI_PIPELINE_URL
    --label com.gitlab.ci.commiturl=$CI_PROJECT_URL/commit/$CI_COMMIT_SHA
    --label com.gitlab.ci.cijoburl=$CI_JOB_URL
    --label com.gitlab.ci.mrurl=$CI_PROJECT_URL/-/merge_requests/$CI_MERGE_REQUEST_ID

build-master:
  stage: build
  environment:
    name: push-to-gitlab-project-registry
  script:
    - | 
      echo "Building and shipping image to $CI_REGISTRY_IMAGE"
      if [[ "$CI_COMMIT_REF_NAME" == "master" ]]; then 
        ADDITIONALTAG="--destination $CI_REGISTRY_IMAGE:latest"
      else
        ADDITIONALTAG=""
      fi
      echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD | base64)\"}}}" > /kaniko/.docker/config.json
      /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG $ADDITIONALTAG $IMAGE_LABELS --label build-date=`date -Iseconds`
  only:
    - master

build:
  stage: build
  #This causes CI CD Variables to be taken from GitLab Project definition for variable scope "push-to-docker-hub", 
  # which overrides CI_REGISTRY, CI_REGISTRY_IMAGE, CI_REGISTRY_USER and CI_REGISTRY_PASSWORD
  environment:
    name: push-to-docker-hub
  script:
    - echo "Building and shipping image to $CI_REGISTRY_IMAGE"
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG $IMAGE_LABELS --label build-date=`date -Iseconds`
  only:
    - push-to-docker-hub
